# Load a model

Each model has been developed within a class in the folder models. The name of the 
module represent the name of the dataset. The model contains a class for each architecture.
The constructor of the calss build the model, split the dataset and set all the hyperparameters of the networks.
So the reproducibility is achived by only instanziating the model.


First you have to chose a model and a dataset.  

for instacne: GIN on the GRID dataset

In [2]:
MODEL = "GIN"
DATASET = "BA_2grid"

# import the model
from models.models_BA_2grid import GIN_framework as framework
# import the dataset
from Datasets.synthetics import BA_2grid

In [3]:
# inizialize the framework
dataset = BA_2grid()
gnn = framework(dataset,device="cpu")

/home/mara/anaconda3/lib/python3.9/site-packages/torch_geometric/data/in_memory_dataset.py:157: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [4]:
# the gnn object contains the train test split and the model.

print(gnn.model)
print(gnn.train_idx)
print(gnn.dataset[gnn.train_idx])

Net(
  (mlp1): Linear(in_features=10, out_features=30, bias=True)
  (conv1): GINConv(nn=Linear(in_features=10, out_features=30, bias=True))
  (mlp2): Linear(in_features=30, out_features=30, bias=True)
  (conv2): GINConv(nn=Linear(in_features=30, out_features=30, bias=True))
  (lin1): Linear(in_features=30, out_features=30, bias=True)
  (lin2): Linear(in_features=30, out_features=2, bias=True)
)
tensor([ 701, 1225,   47,  ...,   40,  423,  494])
BA_2grid(1600)


In [7]:
# right now the model has random weights.
print(gnn.model.mlp1.weight[0])

tensor([-2.5855e-01,  1.3047e-01,  2.6723e-01,  4.9839e-03,  3.0724e-01,
         1.5386e-01, -1.2097e-04,  9.0572e-02,  2.7879e-01,  3.1286e-01],
       dtype=torch.float64, grad_fn=<SelectBackward0>)


In [10]:
#now that the model is instaziated, we have to load the weights
gnn.load_model("models/"+DATASET+"_"+MODEL)
print("we loaded the weights")
# right now the model has trained weights.
print(gnn.model.mlp1.weight[0])

we loaded the weights
tensor([-0.1223,  0.3137,  0.0286, -0.1346,  0.3280,  0.3423, -0.0706,  0.1529,
         0.1649, -0.0715], dtype=torch.float64, grad_fn=<SelectBackward0>)


In [11]:
# we also have a build in function to evaluate the model
gnn.evaluate()

Test Loss: 0.000, Train Acc: 1.000 Test Acc: 1.000
